name = "DisputeIQ"
client_id = "d7026eeb5dedde625fe7ec3d01141928"
application_url = "https://dispute-iq-wcev.vercel.app/install"
embedded = false

[access_scopes]
scopes = "read_orders,read_fulfillments,read_customers,read_shipping"

[webhooks]
api_version = "2024-01"

[auth]
redirect_urls = [
  "https://dispute-iq-wcev.vercel.app/api/shopify-auth/callback"
]

[pos]
embedded = false
